#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run ESLint to check for linting errors before committing
npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix the issues before committing."
  exit 1
fi

# Run Prettier to format the code before committing
npm run prettier
if [ $? -ne 0 ]; then
    echo "Prettier formatting failed. Please fix the issues before committing."
    exit 1
fi

